### ISSUE TITLE
Include the name of the node that actually serves you the interface

### ISSUE THREAD

**Issue by flixi** [lavab/api#110]
https://github.com/lavab/web/issues/313
See here for more info.

**Comment by andreis** [comment]
Not an API issue

**Comment by flixi** [comment]
It is though, since the API /info field needs to provide the information, most noteably.

**Comment by let4be** [comment]
Just to clarify, it depends on what we want to achieve

because there will be:
API server(s)
static content server(s) with all the js/css/html/image stuff

If we want to show static content server name then it can be implemented on nginx via some kind of header I think
If we want to show API server name then we need to modify API

@flixi what do we want to?

**Comment by andreis** [comment]
The email API should have.. email functionality. We shouldn't even have the accounts and emails func under the same API. There might be methods to do what you want, but it's not a `lavab/api` issue.

We can get the name of the node that served the site assets (html/js/css/other) and display it. (also, it's gonna be a node, not a server, since we use openstack to abstract the lower level away)
