### ISSUE TITLE
Username styling

### ISSUE THREAD

**Issue by pzduniak** [lavab/api#97]

**Comment by flixi** [comment]
Yes, for example in prod felix.vlooz becomes felixvlooz.

**Comment by piggyslasher** [comment]
We should do how Google does it. It ignores periods. Like piggy.slasher@gmail.com is the same as piggyslasher@gmail.com

**Comment by andreis** [comment]
That's what I'm saying. We (like Google) remember the username *style*, i.e. that you prefer `hot.stuff@domain.com` instead of `hotstuff@domain.com`. Initially I wanted to preserve capitalisation too (`Hot.Stuff@domain.com`) but I think we shouldn't.

To summarize:

* we remember that a user prefers `abc.def@lavaboom.com`
* when receiving email we ignore periods and capitalisation (`A.b.C` become `abc`)

**Comment by pzduniak** [comment]
I'm starting work on it right now.

**Comment by pzduniak** [comment]
Fixed in 8e3e77418c976918b3742b7899e922887c05c5dd

**Comment by andreis** [comment]
Danke
